apiVersion: v2
name: knative
description: A helm chart for knative
version: 0.1.1
appVersion: 0.1.20
dependencies:
- name: knative-serving
  version: 0.1.20
  repository: cm://app.plural.sh/cm/knative
