apiVersion: v2
name: kafka
description: A helm chart for kafka
version: 0.1.0
appVersion: 0.1.23
dependencies:
- name: kafka
  version: 0.1.23
  repository: cm://app.plural.sh/cm/kafka
  condition: kafka.enabled
