apiVersion: v2
name: monitoring
description: A helm chart for monitoring
version: 0.1.2
appVersion: 0.2.1
dependencies:
- name: monitoring
  version: 0.2.1
  repository: cm://app.plural.sh/cm/monitoring
