apiVersion: v2
name: monitoring
description: A helm chart for monitoring
version: 0.1.1
appVersion: 0.2.0
dependencies:
- name: monitoring
  version: 0.2.0
  repository: cm://app.plural.sh/cm/monitoring
