apiVersion: v2
name: console
description: A helm chart for console
version: 0.1.24
appVersion: 0.7.28
dependencies:
- name: console
  version: 0.7.28
  repository: cm://app.plural.sh/cm/console
  condition: console.enabled
