apiVersion: v2
name: crossplane
description: A helm chart for crossplane
version: 0.1.0
appVersion: 0.1.1
dependencies:
- name: crossplane
  version: 0.1.1
  repository: cm://app.plural.sh/cm/crossplane
