apiVersion: v2
name: crossplane
description: A helm chart for crossplane
version: 0.1.5
appVersion: 0.1.9
dependencies:
- name: crossplane
  version: 0.1.9
  repository: cm://app.plural.sh/cm/crossplane
