apiVersion: v2
name: kubecost
description: A helm chart for kubecost
version: 0.1.1
appVersion: 0.1.22
dependencies:
- name: kubecost
  version: 0.1.22
  repository: cm://app.plural.sh/cm/kubecost
  condition: kubecost.enabled
