apiVersion: v2
name: airbyte
description: A helm chart for airbyte
version: 0.1.0
appVersion: 0.3.5
dependencies:
- name: airbyte
  version: 0.3.5
  repository: file:///Users/david/Plural/plural-artifacts/airbyte/helm/airbyte
  condition: airbyte.enabled
